echo color_ceiling_missing.cub
./cub3D maps/error_maps/color_ceiling_missing.cub
echo color_floor_missing.cub
./cub3D maps/error_maps/color_floor_missing.cub
echo color_parameter_ends_with_coma.cub
./cub3D maps/error_maps/color_parameter_ends_with_coma.cub
echo color_parameter_max_int.cub
./cub3D maps/error_maps/color_parameter_max_int.cub
echo color_parameter_negative.cub
./cub3D maps/error_maps/color_parameter_negative.cub
echo color_parameter_too_long.cub
./cub3D maps/error_maps/color_parameter_too_long.cub
echo color_parameter_too_short.cub
./cub3D maps/error_maps/color_parameter_too_short.cub
echo color_parameter_wrong.cub
./cub3D maps/error_maps/color_parameter_wrong.cub
echo color_set_twice.cub
./cub3D maps/error_maps/color_set_twice.cub
echo file_extension_missing
./cub3D maps/error_maps/file_extension_missing
echo file_extension_wrong.cubs
./cub3D maps/error_maps/file_extension_wrong.cubs
echo map_forbidden_character.cub
./cub3D maps/error_maps/map_forbidden_character.cub
echo map_is_not_last.cub
./cub3D maps/error_maps/map_is_not_last.cub
echo map_is_open1.cub
./cub3D maps/error_maps/map_is_open1.cub
echo map_is_open2.cub
./cub3D maps/error_maps/map_is_open2.cub
echo map_missing.cub
./cub3D maps/error_maps/map_missing.cub
echo map_no_starting_position.cub
./cub3D maps/error_maps/map_no_starting_position.cub
echo map_too_many_starting_positions.cub
./cub3D maps/error_maps/map_too_many_starting_positions.cub
echo texture_file_broken.cub
./cub3D maps/error_maps/texture_file_broken.cub
echo texture_file_chmod_0.cub
./cub3D maps/error_maps/texture_file_chmod_0.cub
echo texture_is_directory.cub
./cub3D maps/error_maps/texture_is_directory.cub
echo texture_missing.cub
./cub3D maps/error_maps/texture_missing.cub
echo texture_parameter_wrong.cub
./cub3D maps/error_maps/texture_parameter_wrong.cub
echo texture_set_twice.cub
./cub3D maps/error_maps/texture_set_twice.cub
